### ISSUE TITLE
[Feature] Add https://copilot.cloud.microsoft

### ISSUE THREAD

**Issue by mmmbvia** [dliedke/ChatGPTExtension#2]
Is it possible to add:
https://copilot.cloud.microsoft

Our organisation have membership there, as part of the office suite.. Its really fast.

Screenshot:
![image](https://github.com/user-attachments/assets/3b8c1e6d-f239-4cc8-a3f4-f2c81ce17110)

**Comment by dliedke** [comment]
I will check the possibility.

Thanks!

**Comment by mmmbvia** [comment]
Thanks!

**Comment by dliedke** [comment]
Hello, I worked for hours but MS Copilot uses #shadow-root nodes to prevent automations.

![image](https://github.com/user-attachments/assets/18355e1f-e87c-494f-9501-5bb5372c0ba0)

Even with advanced AIs to generate code I could not get it working. 

Sorry about that.

I will be rolling back the code and closing this issue.

**Comment by martinandersen3d** [comment]
Looks like they are using web-components? I maybe thing you can access them like this:

```
document.querySelector("[data-spot-im-shadow-host]")
 .shadowRoot.querySelector("#spotim-specific .Typography__product-heading")
 .setAttribute("style", "color: red!important");
```

But i'm not sure :-/

I have made a video to get the selector here:

https://github.com/user-attachments/assets/5a3290cc-92d1-4962-9eff-cf64869ee2a2

Sometimes we do not need AI :D

**Comment by dliedke** [comment]
Thanks, but it does not work


[image: image.png]

Even with a lot of simulations and stuff, the message never appears in the
textarea

function setTextInShadowInput(text) {
    try {
        // Get the main container
        const container = document.querySelector("#cib-container >
cib-serp");
        if (!container) throw new Error("Main container not found");

        // Navigate through shadow DOM to get to the action bar
        const actionBar =
container.shadowRoot.querySelector("#cib-action-bar-main");
        if (!actionBar) throw new Error("Action bar not found");

        // Get to the text input component
        const textInput = actionBar.shadowRoot.querySelector("div > div >
div > div.input-row > cib-text-input");
        if (!textInput) throw new Error("Text input component not found");

        // Get the actual textbox
        const searchbox = textInput.shadowRoot.querySelector("#searchbox");
        if (!searchbox) throw new Error("Searchbox not found");

        // Set the value and inner content
        searchbox.innerText = text;
        searchbox.textContent = text;

        // Create and dispatch input event
        const inputEvent = new InputEvent('input', {
            bubbles: true,
            cancelable: true,
            data: text,
            inputType: 'insertText'
        });
        searchbox.dispatchEvent(inputEvent);

        // Create and dispatch a keyboard event (simulating typing)
        const keyEvent = new KeyboardEvent('keyup', {
            bubbles: true,
            cancelable: true,
            key: 'a',  // Doesn't matter which key
            code: 'KeyA'
        });
        searchbox.dispatchEvent(keyEvent);

        // Force a DOM update by modifying a property
        const temp = searchbox.innerHTML;
        searchbox.innerHTML = text;

        // Try setting it as a contentEditable value
        if (searchbox.isContentEditable) {
            searchbox.innerHTML = text;
            // Create a selection range and set the cursor at the end
            const range = document.createRange();
            const selection = window.getSelection();
            range.selectNodeContents(searchbox);
            range.collapse(false);
            selection.removeAllRanges();
            selection.addRange(range);
        }

        // Focus the element
        searchbox.focus();

        // Also try to update any potential reactive properties
        if (textInput.value !== undefined) {
            textInput.value = text;
        }

        // Dispatch a custom event that might trigger UI updates
        const updateEvent = new CustomEvent('value-changed', {
            detail: { value: text },
            bubbles: true,
            composed: true
        });
        textInput.dispatchEvent(updateEvent);

        return true;
    } catch (error) {
        console.error("Error setting text:", error);
        return false;
    }
}

// Helper function to simulate typing
function simulateTyping(element, text) {
    text.split('').forEach((char, index) => {
        setTimeout(() => {
            element.textContent += char;
            const inputEvent = new InputEvent('input', {
                bubbles: true,
                cancelable: true,
                data: char,
                inputType: 'insertText'
            });
            element.dispatchEvent(inputEvent);
        }, index * 50); // 50ms delay between each character
    });
}

// Try both direct setting and simulated typing
async function setTextWithMultipleMethods(text) {
    try {
        const container = document.querySelector("#cib-container >
cib-serp");
        const actionBar =
container.shadowRoot.querySelector("#cib-action-bar-main");
        const textInput = actionBar.shadowRoot.querySelector("div > div >
div > div.input-row > cib-text-input");
        const searchbox = textInput.shadowRoot.querySelector("#searchbox");

        // Clear existing content first
        searchbox.textContent = '';

        // Try direct setting first
        setTextInShadowInput(text);

        // If that doesn't work, try simulated typing
        setTimeout(() => {
            if (!searchbox.textContent.trim()) {
                console.log("Trying simulated typing...");
                simulateTyping(searchbox, text);
            }
        }, 100);

    } catch (error) {
        console.error("Error:", error);
    }
}

// Usage:
setTextWithMultipleMethods("Hello!");


Em sáb., 9 de nov. de 2024 às 15:57, martinandersen3d <
***@***.***> escreveu:

**Comment by martinandersen3d** [comment]
Thinking 1:
I have a dumb question, but when you consol.log(searchbox) to the console, does the element show up in the console?

else you are maybe running the script before the DOM is fully loaded? I don't know how to run a script after all webcomponent has  been applied..

document.onreadystatechange = function () {
    switch (document.readyState) {
        case "loading":
            console.log("Document is loading.");
            break;
        case "interactive":
            console.log("Document is interactive.");
            break;
        case "complete":
            console.log("Document is fully loaded.");
            break;
    }
};

**Comment by martinandersen3d** [comment]
Thinking 2:
Some maybe things..
https://chatgpt.com/share/67311c45-1014-800c-a4eb-da37fc843488

**Comment by dliedke** [comment]
yes, this worked

function setTextboxValue(value) {
    // Navigate through the shadow DOM hierarchy
    const container = document.querySelector("#cib-container > cib-serp");
    if (!container) return console.error("Container not found");

    const actionBar =
container.shadowRoot.querySelector("#cib-action-bar-main");
    if (!actionBar) return console.error("Action bar not found");

    const textInput = actionBar.shadowRoot.querySelector("div > div > div >
div.input-row > cib-text-input");
    if (!textInput) return console.error("Text input not found");

    const searchbox = textInput.shadowRoot.querySelector("#searchbox");
    if (!searchbox) return console.error("Searchbox not found");

    // Set the value
    searchbox.value = value;

    // Trigger an input event to simulate user typing
    searchbox.dispatchEvent(new Event('input', { bubbles: true }));
}

// Usage example:
setTextboxValue("Your text here");



Em dom., 10 de nov. de 2024 às 17:49, martinandersen3d <
***@***.***> escreveu:

**Comment by dliedke** [comment]
Yes, set and send the prompt

function setTextboxValue(value) {
    // Navigate through the shadow DOM hierarchy
    const container = document.querySelector("#cib-container > cib-serp");
    if (!container) return console.error("Container not found");

    const actionBar =
container.shadowRoot.querySelector("#cib-action-bar-main");
    if (!actionBar) return console.error("Action bar not found");

    const textInput = actionBar.shadowRoot.querySelector("div > div > div >
div.input-row > cib-text-input");
    if (!textInput) return console.error("Text input not found");

    const searchbox = textInput.shadowRoot.querySelector("#searchbox");
    if (!searchbox) return console.error("Searchbox not found");

    // Set the value
    searchbox.value = value;

    // Trigger an input event to simulate user typing
    searchbox.dispatchEvent(new Event('input', { bubbles: true }));
}

function sendPrompt() {
    // Navigate through the shadow DOM hierarchy
    const container = document.querySelector("#cib-container > cib-serp");
    if (!container) return console.error("Container not found");

    const actionBar =
container.shadowRoot.querySelector("#cib-action-bar-main");
    if (!actionBar) return console.error("Action bar not found");

    const sendButton = actionBar.shadowRoot.querySelector("div > div > div
> div.bottom-controls > div > div.bottom-right-controls > div > button");
    if (!sendButton) return console.error("Send button not found");

    // Click the button
    sendButton.click();
}

// Or you can combine them into one function:
function setAndSendPrompt(text) {
    setTextboxValue(text);
    setTimeout(sendPrompt, 100); // Small delay to ensure text is set
before sending
}

// Usage of combined function:
setAndSendPrompt("Hi! How are you?");


Em seg., 11 de nov. de 2024 às 12:17, Daniel Carvalho Liedke <
***@***.***> escreveu:

**Comment by dliedke** [comment]
Hello, I am facing the issue below, I could make it work in the past, but
no longer. I added you to the project

https://github.com/dliedke/ChatGPTExtension/tree/Copilot


[image: image.png]

Can you help please?

Thanks,

Daniel


Em seg., 11 de nov. de 2024 às 12:22, Daniel Carvalho Liedke <
***@***.***> escreveu:
