### ISSUE TITLE
Random pasting of clipboard contents into code when using ChatGPT

### ISSUE THREAD

**Issue by lap202** [dliedke/ChatGPTExtension#3]
Clipboard will randomly be pasted to the code window when using the ChatGPT window.

Can be reproduced by opening and closing the window to change the ChatGPT version or by expanding/closing the side bar.

**Comment by dliedke** [comment]
Thanks, working on a fix!

**Comment by dliedke** [comment]
I can't reproduce this one, please check in F12 developer console

document.querySelectorAll('button.flex.gap-1.items-center.select-none.py-1')

Let me know the results

**Comment by dliedke** [comment]
I found the issue, I will publish a new version

**Comment by dliedke** [comment]
Published version 5.5 with fix for copy code image javascript selector.

Please let me know if issue is fixed now because I can't reproduce it here.

**Comment by lap202** [comment]
Awesome,

Wasn't getting any interesting hits on the selector you provided, but I am seeing some hit on this line that you probably don't want to add listeners too:

public const string GPT_CANVAS_COPY_BUTTON_SELECTOR = "button.h-10.rounded-lg.px-2.text-token-text-secondary";

**Comment by lap202** [comment]
That did the trick.

Thanks again for your work here.

**Comment by dliedke** [comment]
Nice, have a great weekend! 😎
